### PR TITLE
Add Guacamole documentation for users and staff

### PR DESCRIPTION
**Pull request by calvinmclean**
## Description

In this PR I add two new pages: "Guacamole Administration" and "Web Desktop and Web Shell User Guide"

"Guacamole Administration" is a guide for staff that adds background on Guacamole at CyVerse, an explanation of the auth plugin, and a guide for installing Guacamole using Ansible. There is also a section on troubleshooting but that part is WIP.

"Web Desktop and Web Shell User Guide" is for users, complete with GIFs.

These new pages really suffer from issue #29:  Unintended indentation in code blocks. This is another reason it is WIP, I would like to find a fix for that first.

Check it out here: https://calvinmclean.github.io/atmosphere-guides

## Checklist before merging Pull Requests
- [x] Run makefile to compile your changes into the guide (see "Compiling Docs" in README.md)
- [x] Verify that the compiled changes look accurate by viewing the HTML site
- [ ] Have at least one other contributor review and approve your changes

### CODE REVIEW

**Comment by cdosborn** [comment]
The numbering in the components section goes 1, 1, 2.

In many places you're using code blocks where `backticks` would make for easier reading. The following is an example: "Install the extension by moving the jar file to:"

Can you explain this more?
> Remove the first two characters from the ID (I have tried it without shortening the ID, but it did not work).

Should `Null` be `NULL`?

**Comment by calvinmclean** [comment]
I made changes to fix the typos and add a better explanation for the creation of HMAC link. I rebased this branch on master after merging #37 to fix the inline code issues.

Side note: When adding the explanation for shortening the connection UUID, I noticed the reasoning left by the previous dev is kind of hand-wavy, so I plan to look into it to see if I can remove that requirement.

**Comment by calvinmclean** [comment]
Note on the side note: The removal of 2 characters is completely unnecessary and I am removing it from the plugin and from the link generation

So I removed that line from the guide

**Comment by cdosborn** [comment]
Cool. I wonder why it existed in the first place? It seems sort of alarming. You'd think uniquely identifying connections by a random two char string would cause collisions.

**Comment by calvinmclean** [comment]
I'm not sure. The dev left a comment [here](https://github.com/calvinmclean/guacamole-auth-hmac/blob/837513cdbfb343d1006839bd67082dca38f3266d/src/main/java/com/stephensugden/guacamole/net/hmac/HmacAuthenticationProvider.java#L175-L180), but the file it mentions is no longer part of Guacamole repository. It seems like he was making room for some sort of prefix. Also, the ID was originally meant to be integers but we use UUIDs because we are fancy.

**Comment by cdosborn** [comment]
Looks good

I was wrong about 'substring(2)' which I thought limited a string to two characters.

**Pull request merged**
