### PR TITLE
Problem: section out of date, discussion on tagging reflect previous version scheme

### PR DESCRIPTION
**Pull request by lenards**
## Description

With the `v27` release, code name Ancient-Asteroid, we changed the release naming scheme that had be used for roughly 3 years of product life for Atmosphere. This updates the tagging section according to the new release naming strategy. 

## Checklist before merging Pull Requests
- [ ] ~If providing a step-by-step procedure (e.g. a set of commands to run), *try following your own steps*, ensure they produce the intended result~
- [x] Run makefile to compile your changes into the guide (see "Compiling Docs" in README.md)
- [x] Verify that the compiled changes look accurate by viewing the HTML site
- [ ] ~If applicable, [Example link to the PR](https://example.test/doc#new_section) to give context to the documentation~
- [ ] Have at least one other contributor review and approve your changes

### CODE REVIEW

**Comment by c-mart** [comment]
> Atmosphere releases named by a number preceded by a "v"

> The tag-name should be have preceding `v`, _"v for version"_

Why `v27` and not just `27`? I don't see why the `v` is necessary.

Otherwise, looks good. Thanks for contributing to docs!

**Comment by lenards** [comment]
I believe the `v` prefix was discussed in the meeting. I think it is to clarify that his a version number.

**Comment by lenards** [comment]
Merging then.

**Comment by lenards** [comment]
I'm pleased that this was the #27-th pull request.

**Comment by lenards** [comment]
Confirmed that Travis CI committed these changes to `gh-pages`.

**Pull request merged**
